;File info
FILENAME "/home/diogo/Quetzal/output/anomalous2.h5";
POS_DIAG_FREQ 25;
MOM_DIAG_FREQ 200;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 2;
POS_POINTS 1024,512;
MOM_POINTS 200,100;
POS_MIN -50, -25;
POS_MAX 50, 25;
MOM_MIN -2, -1;
MOM_MAX 2, 1;
POS_BOUND "periodic", "periodic";
MOM_BOUND "dirichelet", "dirichelet";
;Species
N_SPECIES 2;
DISP "quadratic", "quadratic";
POS_INIT "noise", "noise";
POS_PARAMS 1, 0.1, 1, 0.1;
MOM_INIT "quadratic fermi", "quadratic fermi";
MOM_PARAMS 0, 0.1, 0.5585, 0, 0, 0.1, -0.5585, 0;
;Fields
N_FIELDS 1;
KERNEL "2Dpoisson";
FORCE "gradient";
FIELD_INIT "gaussian";
FIELD_PARAMS 1, 200, 0, 0;
CHARGES 1, -1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 1000;
DELTAT 0.05;
PADDING 2;
PROCS 33,32;