;File info
FILENAME "./output/cyclotron.h5";
DIAG_FREQ 20;
;Simulation Domain
POS_DIMS 1;
MOM_DIMS 2;
POS_POINTS 128;
MOM_POINTS 51, 51;
POS_MIN -10;
POS_MAX 10;
MOM_MIN -1,-1;
MOM_MAX 1,1;
POS_BOUND "periodic";
MOM_BOUND "dirichelet", "dirichelet";
;Species
N_SPECIES 2;
DISP "quadratic", "quadratic";
POS_INIT "gaussian", "gaussian";
POS_PARAMS 1, 1, 0, 1, 1, 0;
MOM_INIT "quadratic maxwell", "quadratic maxwell";
MOM_PARAMS 1, 0.01, 0.25, 0, 1, 0.01, 0.25, 0;
;Fields
N_FIELDS 2;
KERNEL "fixed", "fixed";
FORCE "magnetic", "electric";
FIELD_INIT "uniform", "uniform";
FIELD_PARAMS 1, -10, 10, 0, -10, 10;
CHARGES 1, 1, -1, -1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 1000;
DELTAT 0.02;
PADDING 2;