;File info
FILENAME "./output/dispersion_2DFermiQuadratic2.h5";
DIAG_FREQ 25;
;Simulation Domain
POS_DIMS 1;
MOM_DIMS 1;
POS_POINTS 512;
MOM_POINTS 100;
POS_MIN -32;
POS_MAX 32;
MOM_MIN -1;
MOM_MAX 1;
POS_BOUND "periodic";
MOM_BOUND "dirichelet";
;Species
N_SPECIES 2;
DISP "quadratic", "quadratic";
POS_INIT "double gaussian", "double gaussian";
POS_PARAMS 0.9998615270, 1000, 0, 0.1, 0.05, 0, 1, 1000, 0, 0.0, 0.05, 1;
MOM_INIT "flattened quadratic fermi", "flattened quadratic fermi";
MOM_PARAMS 0.015, 0.05, 0, 0.015, 0.05, 0;
;Fields
N_FIELDS 1;
KERNEL "2Dpoisson";
FORCE "gradient";
FIELD_INIT "gaussian";
FIELD_PARAMS 1, 200, 0;
CHARGES 1, -1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 100000;
DELTAT 0.02;
PADDING 2;