;File info
FILENAME "/data/dsimoes/Quetzal/output/softcore2D_test.h5";
POS_DIAG_FREQ 200;
MOM_DIAG_FREQ 200000;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 2;
POS_POINTS 32,32;
MOM_POINTS 50,50;
POS_MIN -20,-20;
POS_MAX 20,20;
MOM_MIN -0.3,-0.3;
MOM_MAX 0.3,0.3;
POS_BOUND "periodic","periodic";
MOM_BOUND "dirichelet","dirichelet";
;Species
N_SPECIES 1;
DISP "quadratic";
POS_INIT "double gaussian";
POS_PARAMS 0.9998615270, 1000, 0, 0, 0.1, 0.05, 0, 0;
MOM_INIT "dirac delta";
MOM_PARAMS 5, 0, 0;
;Fields
N_FIELDS 1;
KERNEL "2Dsoftcore";
FORCE "gradient";
FIELD_INIT "gaussian";
FIELD_PARAMS 1, 500, 0, 0;
CHARGES 1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 20000;
DELTAT 0.05;
PADDING 2;
PROCS 2,1;