;File info
FILENAME "/home/diogo/Quetzal/output/softcore1D3.h5";
POS_DIAG_FREQ 25;
MOM_DIAG_FREQ 200;
;Simulation Domain
POS_DIMS 1;
MOM_DIMS 1;
POS_POINTS 512;
MOM_POINTS 100;
POS_MIN -20;
POS_MAX 20;
MOM_MIN -0.3;
MOM_MAX 0.3;
POS_BOUND "periodic";
MOM_BOUND "dirichelet";
;Species
N_SPECIES 1;
DISP "quadratic";
POS_INIT "double gaussian";
POS_PARAMS 0.9998615270, 1000, 0, 0.1, 0.05, 0;
MOM_INIT "dirac delta";
MOM_PARAMS 5, 0;
;Fields
N_FIELDS 1;
KERNEL "2Dsoftcore";
FORCE "gradient";
FIELD_INIT "gaussian";
FIELD_PARAMS 1, 500, 0;
CHARGES 1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 100000;
DELTAT 0.05;
PADDING 2;
PROCS 1;