;File info
FILENAME "/home/diogo/Quetzal/output/softcore1DA.h5";
POS_DIAG_FREQ 25;
MOM_DIAG_FREQ 200;
;Simulation Domain
POS_DIMS 1;
MOM_DIMS 1;
POS_POINTS 1024;
MOM_POINTS 150;
POS_MIN -50;
POS_MAX 50;
MOM_MIN -1;
MOM_MAX 1;
POS_BOUND "periodic";
MOM_BOUND "dirichelet";
;Species
N_SPECIES 1;
DISP "quadratic";
POS_INIT "double gaussian";
POS_PARAMS 1, 1000, 0, 0.1, 0.05, 0;
MOM_INIT "quadratic maxwell";
MOM_PARAMS 1, 0.1, 0;
;Fields
N_FIELDS 1;
KERNEL "2Dsoftcore";
FORCE "gradient";
FIELD_INIT "gaussian";
FIELD_PARAMS 0, 500, 0;
CHARGES 1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 50000;
DELTAT 0.02;
PADDING 2;
PROCS 1;