;File info
FILENAME "/home/diogo/Quetzal/output/parallel_test000.h5";
POS_DIAG_FREQ 100;
MOM_DIAG_FREQ 500;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 1;
POS_POINTS 512, 512;
MOM_POINTS 50;
POS_MIN -16, -16;
POS_MAX 16, 16;
MOM_MIN -1;
MOM_MAX 1;
POS_BOUND "periodic", "periodic";
MOM_BOUND "dirichelet";
;Species
N_SPECIES 1;
DISP "quadratic";
POS_INIT "gaussian";
POS_PARAMS 1, 1, -5, 0;
MOM_INIT "flattened quadratic fermi";
MOM_PARAMS 0, 0.1, 0.5;
;Fields
N_FIELDS 1;
KERNEL "2Dpoisson";
FORCE "gradient";
FIELD_INIT "gaussian";
FIELD_PARAMS 1, 200, 0, 0;
CHARGES 1;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 100;
DELTAT 0.01;
PADDING 2;
PROCS 1, 1;