;File info
FILENAME "/home/diogo/Quetzal/output/transfertest.h5";
POS_DIAG_FREQ 1;
MOM_DIAG_FREQ 2000;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 2;
POS_POINTS 64, 10;
MOM_POINTS 2, 2;
POS_MIN -15, -15;
POS_MAX 15, 15;
MOM_MIN -25, -25;
MOM_MAX 25, 25;
POS_BOUND "periodic", "periodic";
MOM_BOUND "dirichelet", "dirichelet";
;Species
N_SPECIES 2;
DISP "quadratic", "quadratic";
POS_INIT "gaussian", "gaussian";
POS_PARAMS 1, 500, 0, 0, 1, 500, 3, 2;
MOM_INIT "quadratic fermi", "quadratic fermi";
MOM_PARAMS 0, 10, 10, 0, 0, 10, -10, 0;
;Fields
N_FIELDS 1;
TYPE "static";
KERNEL "2Dpoisson";
SOURCE_CHARGES 1, -1;
SOURCE_MOMENTS 0, 0;
DYNAMICS "none";
FORCE "gradient";
FORCE_CHARGES 1, -1;
FIELD_INIT "gaussian";
FIELD_PARAMS 0, 200, 0, 0;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 10000;
DELTAT 0.005;
PADDING 2;
PROCS 4,1;
