;File info
FILENAME "./output/twostream_test.h5";
DIAG_FREQ 50;
;Simulation Domain
POS_DIMS 1;
MOM_DIMS 1;
POS_POINTS 4096;
MOM_POINTS 201;
POS_MIN -60;
POS_MAX 60;
MOM_MIN -2;
MOM_MAX 2;
POS_BOUND "periodic";
MOM_BOUND "dirichelet";
;Species
N_SPECIES 1;
N_FIELDS 1;
DISP "quadratic";
CHARGES 1;
POS_INIT "gaussian";
POS_PARAMS 1, 200, 0;
MOM_INIT "double gaussian";
MOM_PARAMS 0.5, 0.02, 0.5, 0.5, 0.02, -0.5;
;Fields
KERNEL "2Dpoisson";
FORCE "gradient";
FIELD_INIT "uniform";
FIELD_PARAMS 1, 0, 200;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 20000;
DELTAT 0.005;
PADDING 2;