;File info
FILENAME "/home/diogo/Quetzal/output/wallTest.h5";
POS_DIAG_FREQ 25;
MOM_DIAG_FREQ 200;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 2;
POS_POINTS 64, 64;
MOM_POINTS 8, 8;
POS_MIN -50, -50;
POS_MAX 50, 50;
MOM_MIN -2, -2;
MOM_MAX 2, 2;
POS_BOUND "wall", "wall";
MOM_BOUND "dirichelet", "dirichelet";
FIELD_BOUND "periodic", "periodic";
;Species
N_SPECIES 1;
DISP "quadratic";
POS_INIT "gaussian";
POS_PARAMS 1, 1, -20, -40;
MOM_INIT "quadratic maxwell";
MOM_PARAMS 1, 0.0001, 1, 1;
;Fields
N_FIELDS 1;
TYPE "static";
KERNEL "2Dpoisson";
SOURCE_CHARGES 0;
SOURCE_MOMENTS 0;
FIELD_MATRIX 0;
FORCE "gradient";
FORCE_CHARGES 0;
FIELD_INIT "gaussian";
FIELD_PARAMS 0, 200, 0, 0;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 200000;
DELTAT 0.1;
PADDING 2;
PROCS 2,2;