;File info
FILENAME "/projects/F202500002HPCVLABISTUL/dsimoes/Quetzal/output/weibel_quadBandNew.h5";
POS_DIAG_FREQ 200;
MOM_DIAG_FREQ 10000;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 2;
POS_POINTS 240, 240;
MOM_POINTS 50,50;
POS_MIN -55, -55;
POS_MAX 55, 55;
MOM_MIN -1, -1.8;
MOM_MAX 1, 1.8;
POS_BOUND "periodic", "periodic";
MOM_BOUND "dirichelet","dirichelet";
FIELD_BOUND "periodic", "periodic";
;Species
N_SPECIES 1;
DISP "anisotropic quadratic";
POS_INIT "gaussian";
POS_PARAMS 10, 10000, 0, 0;
MOM_INIT "anisotropic quadratic fermi";
MOM_PARAMS 0.1, 0.5, 0.01, 0, 0;
;Fields
N_FIELDS 3;
TYPE "dynamic", "dynamic", "dynamic";
KERNEL "2Dmaxwell", "2Dmaxwell", "2Dmaxwell";
SOURCE_CHARGES 1, 1, 0;
SOURCE_MOMENTS 1, 2, 0;
FIELD_MATRIX 0,0,0, 0,0,1 ,0,1,0, 0,0,-1, 0,0,0, -1,0,0;
FORCE "electricX", "electricY", "magnetic";
FORCE_CHARGES 1, 1, 1;
FIELD_INIT "gaussian", "gaussian", "gaussian";
FIELD_PARAMS 0, 200, 0, 0, 0.0, 0.05, 0, 0, 0, 200, 0, 0;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 50001;
DELTAT 0.05;
PADDING 2;
PROCS 24,16;
