;File info
FILENAME "/home/dsimoes/Quetzal/output/weibel_vac.h5";
POS_DIAG_FREQ 1;
MOM_DIAG_FREQ 200;
;Simulation Domain
POS_DIMS 1;
MOM_DIMS 2;
POS_POINTS 1024;
MOM_POINTS 5,5;
POS_MIN -55;
POS_MAX 55;
MOM_MIN -0.15,-0.15;
MOM_MAX 0.15,0.15;
POS_BOUND "periodic";
MOM_BOUND "dirichelet","dirichelet";
;Species
N_SPECIES 1;
DISP "quadratic";
POS_INIT "gaussian";
POS_PARAMS 0, 200, 0;
MOM_INIT "anisotropic quadratic maxwell";
MOM_PARAMS 1, 0.0005, 0.0005, 0, 0;
;Fields
N_FIELDS 3;
TYPE "dynamic", "dynamic", "dynamic";
KERNEL "2Dmaxwell", "2Dmaxwell", "2Dmaxwell";
SOURCE_CHARGES 1, 1, 0;
SOURCE_MOMENTS 1, 2, 0;
DYNAMICS "2DmaxwellEx", "2DmaxwellEy", "2DmaxwellBz";
FORCE "electricX", "electricY", "magnetic";
FORCE_CHARGES 1, 1, 1;
FIELD_INIT "gaussian", "sine", "gaussian";
FIELD_PARAMS 0, 200, 0, 0, 0.01, 0.57119866, 0, 0.200, 0;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 1000;
DELTAT 0.1;
PADDING 2;
PROCS 1;