;File info
FILENAME "/home/diogo/Quetzal/output/weibel_band.h5";
POS_DIAG_FREQ 500;
MOM_DIAG_FREQ 20000;
;Simulation Domain
POS_DIMS 2;
MOM_DIMS 2;
POS_POINTS 256, 256;
MOM_POINTS 50,50;
POS_MIN -110, -110;
POS_MAX 110, 110;
MOM_MIN -1, -1.5;
MOM_MAX 1, 1.5;
POS_BOUND "periodic", "periodic";
MOM_BOUND "dirichelet","dirichelet";
;Species
N_SPECIES 1;
DISP "anisotropic quadratic";
POS_INIT "gaussian";
POS_PARAMS 1, 1000, 0, 0;
MOM_INIT "anisotropic quadratic fermi";
MOM_PARAMS 0.1, 0.3, 0.01, 0, 0;
;Fields
N_FIELDS 3;
TYPE "dynamic", "dynamic", "dynamic";
KERNEL "2Dmaxwell", "2Dmaxwell", "2Dmaxwell";
SOURCE_CHARGES 1, 1, 0;
SOURCE_MOMENTS 1, 2, 0;
DYNAMICS "2DmaxwellEx", "2DmaxwellEy", "2DmaxwellBz";
FORCE "electricX", "electricY", "magnetic";
FORCE_CHARGES 1, 1, 1;
FIELD_INIT "gaussian", "gaussian", "gaussian";
FIELD_PARAMS 0, 200, 0, 0, 0.001, 0.05, 0, 0, 0, 200, 0, 0;
;Algorithm parameters
PUSHER "runge kutta";
OPER "finite volume";
N_TIMESTEPS 100001;
DELTAT 0.025;
PADDING 2;
PROCS 8,8;